import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext.jsx";
import { ThemeProvider, CssBaseline } from "@mui/material";
import theme from "../theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Monitoreo climático",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
